// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...yyyyyyyuyyyyyuuuuuuuuuuuuuuuuuu
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMYkHCPo-XZguRWPPkbwlQmpO6Hyqw7t8',
    appId: '1:40178892186:web:351cd76ac2122529944e23',
    messagingSenderId: '40178892186',
    projectId: 'derma-visuals',
    authDomain: 'derma-visuals.firebaseapp.com',
    storageBucket: 'derma-visuals.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuRBMEYz704SvAfrtfTpdPNAJcZNFE9is',
    appId: '1:40178892186:android:d81f2f1bd06b588a944e23',
    messagingSenderId: '40178892186',
    projectId: 'derma-visuals',
    storageBucket: 'derma-visuals.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUgaeBu2yptAcHhcrgbCSp26PWUprCNko',
    appId: '1:40178892186:ios:aadbb00e44de497f944e23',
    messagingSenderId: '40178892186',
    projectId: 'derma-visuals',
    storageBucket: 'derma-visuals.appspot.com',
    iosBundleId: 'com.example.skinskan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUgaeBu2yptAcHhcrgbCSp26PWUprCNko',
    appId: '1:40178892186:ios:970dbb3c9e5c1fcd944e23',
    messagingSenderId: '40178892186',
    projectId: 'derma-visuals',
    storageBucket: 'derma-visuals.appspot.com',
    iosBundleId: 'com.example.skinskan.RunnerTests',
  );
}
